version: "3.9"

services:

  rabbitmq:
    image: "rabbitmq:3.11-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    depends_on:
      - rabbitmq

  flower:
    build:
      context: .
      dockerfile: flower.Dockerfile
    ports:
      - "5555:5555"
    depends_on:
      - worker
      - rabbitmq
      - redis

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    depends_on:
      - rabbitmq
      - redis

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8010:8000"
    depends_on:
      - worker
      - flower
      - rabbitmq
      - redis